-keep class com.example.smsgateway.** { *; }
-keepclassmembers class com.example.smsgateway.** { *; }
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class org.json.** { *; }
-keepclassmembers class org.json.** { *; }
